name: push pipeline
on:
  push:
    branches: [ master ]   # Runs when code is pushed to the 'main' branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
    
      - name: Lint code
        run: npx run lint
        continue-on-error: true

      - name: Run tests
        run: npm test

      - name: Notify build status
        if: ${{ success() }}
        run: echo "Build succeeded!"

      - name: Notify build failure
        if: ${{ failure() }}
        run: echo "Build failed!"

